export const KEUS_DEVICE_METADATA = [
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZES1P",
    "deviceCategory": "KZES",
    "dmDeviceCategory": 1,
    "dmDeviceType": 1,
    "bleDeviceName": "KZES01",
    "categoryDisplayName": "Embedded Switch",
    "typeDisplayName": "1 port",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "es_1p_",
    "KPN_Name": "ES102",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZES1PM",
    "deviceCategory": "KZES",
    "dmDeviceCategory": 1,
    "dmDeviceType": 17,
    "bleDeviceName": "KZESM1",
    "categoryDisplayName": "Embedded Switch",
    "typeDisplayName": "1 port",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "es_1p_",
    "KPN_Name": "ES102",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZES1PH",
    "deviceCategory": "KZES",
    "dmDeviceCategory": 1,
    "dmDeviceType": 7,
    "bleDeviceName": "KZES01H",
    "categoryDisplayName": "Embedded Switch",
    "typeDisplayName": "1 port hongfa",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "es_1ph_",
    "KPN_Name": "ES102",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZES1PHM",
    "deviceCategory": "KZES",
    "dmDeviceCategory": 1,
    "dmDeviceType": 23,
    "bleDeviceName": "KZESM1H",
    "categoryDisplayName": "Embedded Switch",
    "typeDisplayName": "1 port hongfa",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "es_1ph_",
    "KPN_Name": "ES102",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZES2P",
    "deviceCategory": "KZES",
    "dmDeviceCategory": 1,
    "dmDeviceType": 2,
    "bleDeviceName": "KZES02",
    "categoryDisplayName": "Embedded Switch",
    "typeDisplayName": "2 port",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "es_2p_",
    "KPN_Name": "ES202",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZES2PM",
    "deviceCategory": "KZES",
    "dmDeviceCategory": 1,
    "dmDeviceType": 18,
    "bleDeviceName": "KZESM2",
    "categoryDisplayName": "Embedded Switch",
    "typeDisplayName": "2 port",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "es_2p_",
    "KPN_Name": "ES202",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZES4P",
    "deviceCategory": "KZES",
    "dmDeviceCategory": 1,
    "dmDeviceType": 3,
    "bleDeviceName": "KZES04",
    "categoryDisplayName": "Embedded Switch",
    "typeDisplayName": "4 port",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "es_4p_",
    "KPN_Name": "ES402",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZES4PM",
    "deviceCategory": "KZES",
    "dmDeviceCategory": 1,
    "dmDeviceType": 19,
    "bleDeviceName": "KZESM4",
    "categoryDisplayName": "Embedded Switch",
    "typeDisplayName": "4 port",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "es_4p_",
    "KPN_Name": "ES402",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZES1PIL",
    "deviceCategory": "KZES",
    "dmDeviceCategory": 1,
    "dmDeviceType": 4,
    "bleDeviceName": "KZILD0P",
    "categoryDisplayName": "Embedded Switch",
    "typeDisplayName": "Inline Dimmer",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "es_ild_",
    "KPN_Name": "LCIPD01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZES1PIL",
    "deviceCategory": "KZES",
    "dmDeviceCategory": 1,
    "dmDeviceType": 4,
    "bleDeviceName": "KZILDOP",
    "categoryDisplayName": "Embedded Switch",
    "typeDisplayName": "Inline Dimmer",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "es_ild_",
    "KPN_Name": "LCIPD01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZES1PILM1",
    "deviceCategory": "KZES",
    "dmDeviceCategory": 1,
    "dmDeviceType": 20,
    "bleDeviceName": "KZILDMP",
    "categoryDisplayName": "Embedded Switch",
    "typeDisplayName": "Inline Dimmer",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "es_ild_",
    "KPN_Name": "LCIPD01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZES6PSC",
    "deviceCategory": "KZES",
    "dmDeviceCategory": 1,
    "dmDeviceType": 5,
    "bleDeviceName": "KZSPC01",
    "categoryDisplayName": "Embedded Switch",
    "typeDisplayName": "Sprinkler Controller",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "spc_",
    "KPN_Name": "SC6DR01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZES6PSCM",
    "deviceCategory": "KZES",
    "dmDeviceCategory": 1,
    "dmDeviceType": 21,
    "bleDeviceName": "KZSPCM1",
    "categoryDisplayName": "Embedded Switch",
    "typeDisplayName": "Sprinkler Controller",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "spc_",
    "KPN_Name": "SC6DR01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZES6DR",
    "deviceCategory": "KZES",
    "dmDeviceCategory": 1,
    "dmDeviceType": 24,
    "bleDeviceName": "KZES6DR",
    "categoryDisplayName": "Embedded Switch",
    "typeDisplayName": "Din Rail",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "es6dr_",
    "KPN_Name": "SC6DR01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZES1PO",
    "deviceCategory": "KZES",
    "dmDeviceCategory": 1,
    "dmDeviceType": 241,
    "bleDeviceName": "",
    "categoryDisplayName": "Embedded Switch",
    "typeDisplayName": "1 port cc2530",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "cc2530",
    "fileName": "",
    "KPN_Name": "ES102",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZES2PO",
    "deviceCategory": "KZES",
    "dmDeviceCategory": 1,
    "dmDeviceType": 242,
    "bleDeviceName": "",
    "categoryDisplayName": "Embedded Switch",
    "typeDisplayName": "2 port cc2530",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "cc2530",
    "fileName": "",
    "KPN_Name": "ES202",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZES4PO",
    "deviceCategory": "KZES",
    "dmDeviceCategory": 1,
    "dmDeviceType": 243,
    "bleDeviceName": "",
    "categoryDisplayName": "Embedded Switch",
    "typeDisplayName": "4 port cc2530",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "cc2530",
    "fileName": "",
    "KPN_Name": "ES402",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZCC01",
    "deviceCategory": "KZCC",
    "dmDeviceCategory": 2,
    "dmDeviceType": 1,
    "bleDeviceName": "KZCC01",
    "categoryDisplayName": "Curtain Controller",
    "typeDisplayName": "Sliding curtain",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "curtain_cc",
    "KPN_Name": "CCDM02",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZCC02",
    "deviceCategory": "KZCC",
    "dmDeviceCategory": 2,
    "dmDeviceType": 2,
    "bleDeviceName": "KZRC01",
    "categoryDisplayName": "Curtain Controller",
    "typeDisplayName": "Rolling curtain",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "rcurtain_",
    "KPN_Name": "CCEM02",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZCCM1",
    "deviceCategory": "KZCC",
    "dmDeviceCategory": 2,
    "dmDeviceType": 17,
    "bleDeviceName": "KZCCM1",
    "categoryDisplayName": "Curtain Controller",
    "typeDisplayName": "Sliding curtain",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "curtain_cc",
    "KPN_Name": "CCDM02",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZCCM2",
    "deviceCategory": "KZCC",
    "dmDeviceCategory": 2,
    "dmDeviceType": 18,
    "bleDeviceName": "KZRCM1",
    "categoryDisplayName": "Curtain Controller",
    "typeDisplayName": "Rolling curtain",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "rcurtain_",
    "KPN_Name": "CCEM02",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZCCF2",
    "deviceCategory": "KZCC",
    "dmDeviceCategory": 2,
    "dmDeviceType": 242,
    "bleDeviceName": "",
    "categoryDisplayName": "Curtain Controller",
    "typeDisplayName": "Rolling curtain cc2530",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "cc2530",
    "fileName": "",
    "KPN_Name": "CCEM02",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZESS10",
    "deviceCategory": "KZESS",
    "dmDeviceCategory": 3,
    "dmDeviceType": 0,
    "bleDeviceName": "",
    "categoryDisplayName": "Scene Control",
    "typeDisplayName": "Global Scene Switch",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZESS01",
    "deviceCategory": "KZESS",
    "dmDeviceCategory": 3,
    "dmDeviceType": 1,
    "bleDeviceName": "",
    "categoryDisplayName": "Scene Control",
    "typeDisplayName": "Local Scene Switch",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZSW01",
    "deviceCategory": "KZSW",
    "dmDeviceCategory": 3,
    "dmDeviceType": 2,
    "bleDeviceName": "KZSW01",
    "categoryDisplayName": "Scene Wizard",
    "typeDisplayName": "Scene Wizard",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "scene_wizard",
    "KPN_Name": "SWXX01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZCW01",
    "deviceCategory": "KZCW",
    "dmDeviceCategory": 3,
    "dmDeviceType": 3,
    "bleDeviceName": "KZCW01",
    "categoryDisplayName": "Curtain Wizard",
    "typeDisplayName": "Curtain Wizard",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "curtain_wizard_",
    "KPN_Name": "CWXX01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZSWM1",
    "deviceCategory": "KZSW",
    "dmDeviceCategory": 3,
    "dmDeviceType": 18,
    "bleDeviceName": "KZSWM1",
    "categoryDisplayName": "Scene Wizard",
    "typeDisplayName": "Scene Wizard",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "scene_wizard",
    "KPN_Name": "SWXX01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZCWM1",
    "deviceCategory": "KZCW",
    "dmDeviceCategory": 3,
    "dmDeviceType": 19,
    "bleDeviceName": "KZCWM1",
    "categoryDisplayName": "Curtain Wizard",
    "typeDisplayName": "Curtain Wizard",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "curtain_wizard_",
    "KPN_Name": "CWXX01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZSC4PM1",
    "deviceCategory": "KZSC",
    "dmDeviceCategory": 4,
    "dmDeviceType": 19,
    "bleDeviceName": "KZSC4ZPM",
    "categoryDisplayName": "Smart Console",
    "typeDisplayName": "Smart Console Medium Proximity",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "sc_MZP_",
    "KPN_Name": "SCMXX01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZSC7PM1",
    "deviceCategory": "KZSC",
    "dmDeviceCategory": 4,
    "dmDeviceType": 20,
    "bleDeviceName": "KZSC7ZPM",
    "categoryDisplayName": "Smart Console",
    "typeDisplayName": "Smart Console Large Proximity",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "sc_LZP_",
    "KPN_Name": "SCLXX01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZSC4C",
    "deviceCategory": "KZSC",
    "dmDeviceCategory": 4,
    "dmDeviceType": 2,
    "bleDeviceName": "KZSC4C",
    "categoryDisplayName": "Smart Console",
    "typeDisplayName": "Smart Console Medium",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "sc_M_",
    "KPN_Name": "SCMXX01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZSC7C",
    "deviceCategory": "KZSC",
    "dmDeviceCategory": 4,
    "dmDeviceType": 1,
    "bleDeviceName": "KZSC7C",
    "categoryDisplayName": "Smart Console",
    "typeDisplayName": "Smart Console Large",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "sc_L_",
    "KPN_Name": "SCLXX01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZSC4M1",
    "deviceCategory": "KZSC",
    "dmDeviceCategory": 4,
    "dmDeviceType": 18,
    "bleDeviceName": "KZSC4M",
    "categoryDisplayName": "Smart Console",
    "typeDisplayName": "Smart Console Medium",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "sc_M_",
    "KPN_Name": "SCMXX01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZSC7M1",
    "deviceCategory": "KZSC",
    "dmDeviceCategory": 4,
    "dmDeviceType": 17,
    "bleDeviceName": "KZSC7M",
    "categoryDisplayName": "Smart Console",
    "typeDisplayName": "Smart Console Large",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "sc_L_",
    "KPN_Name": "SCLXX01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZSCMXX01P",
    "deviceCategory": "KZSC",
    "dmDeviceCategory": 4,
    "dmDeviceType": 21,
    "bleDeviceName": "KZSCMXX01P",
    "categoryDisplayName": "Smart Console",
    "typeDisplayName": "SCM V1",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "scm_v1",
    "KPN_Name": "KZSCMXX01P",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZSCLXX01P",
    "deviceCategory": "KZSC",
    "dmDeviceCategory": 4,
    "dmDeviceType": 22,
    "bleDeviceName": "KZSCLXX01P",
    "categoryDisplayName": "Smart Console",
    "typeDisplayName": "SCL V1",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "scl_v1",
    "KPN_Name": "KZSCLXX01P",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZSCMXX02P",
    "deviceCategory": "KZSC",
    "dmDeviceCategory": 4,
    "dmDeviceType": 33,
    "bleDeviceName": "KZSCMXX02P",
    "categoryDisplayName": "Smart Console",
    "typeDisplayName": "SCM V2",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "scm_v2",
    "KPN_Name": "KZSCMXX02P",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZSCMXX02M",
    "deviceCategory": "KZSC",
    "dmDeviceCategory": 4,
    "dmDeviceType": 35,
    "bleDeviceName": "KZSCMXX02M",
    "categoryDisplayName": "Smart Console",
    "typeDisplayName": "SCM V2 Metal",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "scm_metal_v2",
    "KPN_Name": "KZSCMXX02M",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZSCSXX02P",
    "deviceCategory": "KZSC",
    "dmDeviceCategory": 4,
    "dmDeviceType": 34,
    "bleDeviceName": "KZSCSXX02P",
    "categoryDisplayName": "Smart Console",
    "typeDisplayName": "SCS V2",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "scs_v2",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZSCSXX02M",
    "deviceCategory": "KZSC",
    "dmDeviceCategory": 4,
    "dmDeviceType": 36,
    "bleDeviceName": "KZSCSXX02M",
    "categoryDisplayName": "Smart Console",
    "typeDisplayName": "SCS V2 Metal",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "scs_metal_v2",
    "KPN_Name": "KZSCSXX02M",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZDD01",
    "deviceCategory": "KZDD",
    "dmDeviceCategory": 5,
    "dmDeviceType": 1,
    "bleDeviceName": "KZELD01",
    "categoryDisplayName": "Zigbee Drivers",
    "typeDisplayName": "E-Driver",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "edriver_",
    "KPN_Name": "KCCZDE",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZDD02",
    "deviceCategory": "KZDD",
    "dmDeviceCategory": 5,
    "dmDeviceType": 2,
    "bleDeviceName": "KZLD01",
    "categoryDisplayName": "Zigbee Drivers",
    "typeDisplayName": "S-Driver",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "sdriver_",
    "KPN_Name": "KCCZDS",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZDDERM1",
    "deviceCategory": "KZDD",
    "dmDeviceCategory": 5,
    "dmDeviceType": 17,
    "bleDeviceName": "KZELDM1",
    "categoryDisplayName": "Zigbee Drivers",
    "typeDisplayName": "E-Driver",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "edriver_",
    "KPN_Name": "KCCZDE",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZDDSATM1",
    "deviceCategory": "KZDD",
    "dmDeviceCategory": 5,
    "dmDeviceType": 18,
    "bleDeviceName": "KZLDM1",
    "categoryDisplayName": "Zigbee Drivers",
    "typeDisplayName": "S-Driver",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "sdriver_",
    "KPN_Name": "KCCZDS",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZACFC01",
    "deviceCategory": "KZACFC",
    "dmDeviceCategory": 6,
    "dmDeviceType": 1,
    "bleDeviceName": "KZACFC01",
    "categoryDisplayName": "AC Fan Controller",
    "typeDisplayName": "AC Fan",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "fan_ac_",
    "KPN_Name": "FCACX01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZDCFC01",
    "deviceCategory": "KZDCFC",
    "dmDeviceCategory": 6,
    "dmDeviceType": 2,
    "bleDeviceName": "KZDCFC01",
    "categoryDisplayName": "DC Fan Controller",
    "typeDisplayName": "DC 38W Fan",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "fan_dc_cc",
    "KPN_Name": "FCDCC3801",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZDCFC55",
    "deviceCategory": "KZDCFC",
    "dmDeviceCategory": 6,
    "dmDeviceType": 3,
    "bleDeviceName": "KZDCFC55",
    "categoryDisplayName": "DC Fan Controller",
    "typeDisplayName": "DC 55W Fan",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "fan_dc_55w_",
    "KPN_Name": "FCDCC5501",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZACFCM1",
    "deviceCategory": "KZACFC",
    "dmDeviceCategory": 6,
    "dmDeviceType": 17,
    "bleDeviceName": "KZACFCM1",
    "categoryDisplayName": "AC Fan Controller",
    "typeDisplayName": "AC Fan",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "fan_ac_",
    "KPN_Name": "FCACX01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZDCFCM1",
    "deviceCategory": "KZDCFC",
    "dmDeviceCategory": 6,
    "dmDeviceType": 18,
    "bleDeviceName": "KZDCFCM1",
    "categoryDisplayName": "DC Fan Controller",
    "typeDisplayName": "DC 38W Fan",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "fan_dc_cc",
    "KPN_Name": "FCDCC3801",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZDCFCM55",
    "deviceCategory": "KZDCFC",
    "dmDeviceCategory": 6,
    "dmDeviceType": 19,
    "bleDeviceName": "KZDCFCM55",
    "categoryDisplayName": "DC Fan Controller",
    "typeDisplayName": "DC 55W Fan",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "fan_dc_55w_",
    "KPN_Name": "FCDCC5501",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZIRB01",
    "deviceCategory": "KZIRB",
    "dmDeviceCategory": 7,
    "dmDeviceType": 1,
    "bleDeviceName": "KZIRB01",
    "categoryDisplayName": "IR Blaster",
    "typeDisplayName": "IR Blaster",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "irblaster_",
    "KPN_Name": "SIRX01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZIRBM1",
    "deviceCategory": "KZIRB",
    "dmDeviceCategory": 7,
    "dmDeviceType": 17,
    "bleDeviceName": "KZIRBM1",
    "categoryDisplayName": "IR Blaster",
    "typeDisplayName": "IR Blaster",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "irblaster_",
    "KPN_Name": "SIRX01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZRGBWWA01",
    "deviceCategory": "KZRGBWWA",
    "dmDeviceCategory": 8,
    "dmDeviceType": 1,
    "bleDeviceName": "KZCV01",
    "categoryDisplayName": "CV Strip",
    "typeDisplayName": "RGBWWA",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "cvstrip_cc",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZRGBA",
    "deviceCategory": "KZRGBWWA",
    "dmDeviceCategory": 8,
    "dmDeviceType": 2,
    "bleDeviceName": "KZRGBA01",
    "categoryDisplayName": "CV Strip",
    "typeDisplayName": "RGB Addressable",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZRGBWWA02",
    "deviceCategory": "KZRGBWWA",
    "dmDeviceCategory": 8,
    "dmDeviceType": 3,
    "bleDeviceName": "KZCV02",
    "categoryDisplayName": "CV Strip",
    "typeDisplayName": "RGBWWA-HW2",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "cvstrip_v2",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZRGBWWAM1",
    "deviceCategory": "KZRGBWWA",
    "dmDeviceCategory": 8,
    "dmDeviceType": 17,
    "bleDeviceName": "KZCVM1",
    "categoryDisplayName": "CV Strip",
    "typeDisplayName": "RGBWWA",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "cvstrip_cc",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZRGBWWAM2",
    "deviceCategory": "KZRGBWWA",
    "dmDeviceCategory": 8,
    "dmDeviceType": 19,
    "bleDeviceName": "KZCVM2",
    "categoryDisplayName": "CV Strip",
    "typeDisplayName": "RGBWWA-HW2",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "cvstrip_v2",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZCS01",
    "deviceCategory": "KZCS",
    "dmDeviceCategory": 9,
    "dmDeviceType": 0,
    "bleDeviceName": "",
    "categoryDisplayName": "Contact Sensor",
    "typeDisplayName": "Contact Sensor",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZRE01",
    "deviceCategory": "KZRE",
    "dmDeviceCategory": 10,
    "dmDeviceType": 1,
    "bleDeviceName": "KZE01",
    "categoryDisplayName": "Zigbee Range Extender",
    "typeDisplayName": "Zigbee Range Extender",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "zig_extender_",
    "KPN_Name": "SMG100",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZREM1",
    "deviceCategory": "KZRE",
    "dmDeviceCategory": 10,
    "dmDeviceType": 17,
    "bleDeviceName": "KZEM1",
    "categoryDisplayName": "Zigbee Range Extender",
    "typeDisplayName": "Zigbee Range Extender",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "zig_extender_",
    "KPN_Name": "SMG100",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZNPR",
    "deviceCategory": "HUB",
    "dmDeviceCategory": 99,
    "dmDeviceType": 1,
    "bleDeviceName": "KZNPR",
    "categoryDisplayName": "HUB",
    "typeDisplayName": "HUB",
    "isOtaUpgradeable": false,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "znp_",
    "KPN_Name": "SH01",
    "KPN_List": "",
    "hidden": true
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZNPP",
    "deviceCategory": "HUB",
    "dmDeviceCategory": 99,
    "dmDeviceType": 2,
    "bleDeviceName": "KZNPP",
    "categoryDisplayName": "HUB",
    "typeDisplayName": "HUB",
    "isOtaUpgradeable": false,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "znp_",
    "KPN_Name": "SH01",
    "KPN_List": "",
    "hidden": true
  },
  {
    "protocol": "IP",
    "deviceType": "KEHVAC02",
    "deviceCategory": "KEHVAC",
    "dmDeviceCategory": 0,
    "dmDeviceType": 0,
    "bleDeviceName": "",
    "categoryDisplayName": "HVAC",
    "typeDisplayName": "Cool Master Wall",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "IP",
    "deviceType": "KIPHVACCM01",
    "deviceCategory": "KIPHVACCM",
    "dmDeviceCategory": 0,
    "dmDeviceType": 0,
    "bleDeviceName": "",
    "categoryDisplayName": "HVAC",
    "typeDisplayName": "Cool Master Roof Top",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "IP",
    "deviceType": "UNIFICCTV01",
    "deviceCategory": "UNIFICCTV",
    "dmDeviceCategory": 0,
    "dmDeviceType": 0,
    "bleDeviceName": "",
    "categoryDisplayName": "CCTV",
    "typeDisplayName": "Unifi CCTV",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE-GM",
    "deviceType": "KZBCR01",
    "deviceCategory": "KZBCR",
    "dmDeviceCategory": 2,
    "dmDeviceType": 3,
    "bleDeviceName": "KZRBCR",
    "categoryDisplayName": "Deep Relay Curtain Controller",
    "typeDisplayName": "Deep Relay curtain",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "rbc",
    "KPN_Name": "CCEM02",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE-GM",
    "deviceType": "KZBCR02",
    "deviceCategory": "KZBCR",
    "dmDeviceCategory": 2,
    "dmDeviceType": 19,
    "bleDeviceName": "KZRBCM",
    "categoryDisplayName": "Deep Relay Curtain Controller",
    "typeDisplayName": "Deep Relay curtain",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "rbc",
    "KPN_Name": "CCEM02",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE-GM",
    "deviceType": "KZBCS01",
    "deviceCategory": "KZBCS",
    "dmDeviceCategory": 2,
    "dmDeviceType": 4,
    "bleDeviceName": "KZSBCR",
    "categoryDisplayName": "Deep Slider Curtain Controller",
    "typeDisplayName": "Deep Slider curtain",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "sbc",
    "KPN_Name": "CCDM02",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE-GM",
    "deviceType": "KZBCS02",
    "deviceCategory": "KZBCS",
    "dmDeviceCategory": 2,
    "dmDeviceType": 20,
    "bleDeviceName": "KZSBCM",
    "categoryDisplayName": "Deep Slider Curtain Controller",
    "typeDisplayName": "Deep Slider curtain",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "sbc",
    "KPN_Name": "CCDM02",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE-GM",
    "deviceType": "KZCV301",
    "deviceCategory": "KZCV3",
    "dmDeviceCategory": 8,
    "dmDeviceType": 4,
    "bleDeviceName": "KZCV3R",
    "categoryDisplayName": "CV3",
    "typeDisplayName": "CV3",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "cv3_",
    "KPN_Name": "LCRTS301",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE-GM",
    "deviceType": "KZCV302",
    "deviceCategory": "KZCV3",
    "dmDeviceCategory": 8,
    "dmDeviceType": 20,
    "bleDeviceName": "KZCV3M",
    "categoryDisplayName": "CV3",
    "typeDisplayName": "CV3",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "cv3_",
    "KPN_Name": "LCRTS301",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE-GM",
    "deviceType": "KZCV601",
    "deviceCategory": "KZCV6",
    "dmDeviceCategory": 8,
    "dmDeviceType": 5,
    "bleDeviceName": "KZCV6R",
    "categoryDisplayName": "CV6",
    "typeDisplayName": "CV6",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "cv6_",
    "KPN_Name": "LCRGBWWA02",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE-GM",
    "deviceType": "KZCV602",
    "deviceCategory": "KZCV6",
    "dmDeviceCategory": 8,
    "dmDeviceType": 21,
    "bleDeviceName": "KZCV6M",
    "categoryDisplayName": "CV6",
    "typeDisplayName": "CV6",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "cv6_",
    "KPN_Name": "LCRGBWWA02",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE-GM",
    "deviceType": "KZCVADDR01",
    "deviceCategory": "KZCVADDR",
    "dmDeviceCategory": 8,
    "dmDeviceType": 22,
    "bleDeviceName": "KZCVAM",
    "categoryDisplayName": "CV Addressable",
    "typeDisplayName": "Addressable Strip",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "cva_",
    "KPN_Name": "LCAS01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE-GM",
    "deviceType": "KZESPTP",
    "deviceCategory": "KZESPT",
    "dmDeviceCategory": 1,
    "dmDeviceType": 6,
    "bleDeviceName": "KZESGR",
    "categoryDisplayName": "Embedded Gate",
    "typeDisplayName": "Push Trigger Controller",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "es_gate_",
    "KPN_Name": "GCDR01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE-GM",
    "deviceType": "KZESPTPM",
    "deviceCategory": "KZESPT",
    "dmDeviceCategory": 1,
    "dmDeviceType": 22,
    "bleDeviceName": "KZESGM",
    "categoryDisplayName": "Embedded Gate",
    "typeDisplayName": "Push Trigger Controller",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "es_gate_",
    "KPN_Name": "GCDR01",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZND01",
    "deviceCategory": "KZND",
    "dmDeviceCategory": 0,
    "dmDeviceType": 0,
    "bleDeviceName": "",
    "categoryDisplayName": "Zigbee Nondimmable Drivers",
    "typeDisplayName": "Zigbee Nondimmable Drivers",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": "",
    "hidden": true
  },
  {
    "protocol": "KEUSZIGBEE-DALI",
    "deviceType": "KDDD01",
    "deviceCategory": "KDDD",
    "dmDeviceCategory": 0,
    "dmDeviceType": 0,
    "bleDeviceName": "",
    "categoryDisplayName": "Dali Dimmable Drivers",
    "typeDisplayName": "Dali Dimmable Drivers",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE-DALI",
    "deviceType": "KDCTD01",
    "deviceCategory": "KDCTD",
    "dmDeviceCategory": 0,
    "dmDeviceType": 0,
    "bleDeviceName": "",
    "categoryDisplayName": "Dali Color Tunable Driver",
    "typeDisplayName": "Dali Color Tunable Driver",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE-DALI",
    "deviceType": "KDND01",
    "deviceCategory": "KDND",
    "dmDeviceCategory": 0,
    "dmDeviceType": 0,
    "bleDeviceName": "",
    "categoryDisplayName": "Dali Nondimmable Drivers",
    "typeDisplayName": "Dali Nondimmable Drivers",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": "",
    "hidden": true
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZID01",
    "deviceCategory": "KZID",
    "dmDeviceCategory": 0,
    "dmDeviceType": 0,
    "bleDeviceName": "",
    "categoryDisplayName": "Inlinedimmer",
    "typeDisplayName": "Inlinedimmer",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": "",
    "hidden": true
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZGC01",
    "deviceCategory": "KZGC",
    "dmDeviceCategory": 11,
    "dmDeviceType": 1,
    "bleDeviceName": "KZGC01",
    "categoryDisplayName": "Gate Controller",
    "typeDisplayName": "Gate Controller",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652r",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZGC02",
    "deviceCategory": "KZGC",
    "dmDeviceCategory": 11,
    "dmDeviceType": 2,
    "bleDeviceName": "KZGCM",
    "categoryDisplayName": "Gate Controller",
    "typeDisplayName": "Gate Controller",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZSC7C",
    "deviceCategory": "KZSC",
    "dmDeviceCategory": 4,
    "dmDeviceType": 1,
    "bleDeviceName": "KZSC7C_SM3",
    "categoryDisplayName": "Smart Console",
    "typeDisplayName": "Smart Console Large V2",
    "isOtaUpgradeable": true,
    "isFlashable": false,
    "chipType": "cc2652r",
    "fileName": "sc_L_",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZSC4C",
    "deviceCategory": "KZSC",
    "dmDeviceCategory": 4,
    "dmDeviceType": 2,
    "bleDeviceName": "KZSC4C_SM3",
    "categoryDisplayName": "Smart Console",
    "typeDisplayName": "Smart Console Medium V2",
    "isOtaUpgradeable": true,
    "isFlashable": false,
    "chipType": "cc2652r",
    "fileName": "sc_M_",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZSC7C",
    "deviceCategory": "KZSC",
    "dmDeviceCategory": 4,
    "dmDeviceType": 1,
    "bleDeviceName": "KZSC7C_SM2",
    "categoryDisplayName": "Smart Console",
    "typeDisplayName": "Smart Console Large V2",
    "isOtaUpgradeable": true,
    "isFlashable": false,
    "chipType": "cc2652r",
    "fileName": "sc_L_",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZSC4C",
    "deviceCategory": "KZSC",
    "dmDeviceCategory": 4,
    "dmDeviceType": 2,
    "bleDeviceName": "KZSC4C_SM2",
    "categoryDisplayName": "Smart Console",
    "typeDisplayName": "Smart Console Medium V2",
    "isOtaUpgradeable": true,
    "isFlashable": false,
    "chipType": "cc2652r",
    "fileName": "sc_M_",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZES1PIL",
    "deviceCategory": "KZES",
    "dmDeviceCategory": 1,
    "dmDeviceType": 4,
    "bleDeviceName": "KZILD01",
    "categoryDisplayName": "Embedded Switch",
    "typeDisplayName": "Inline Dimmer V2",
    "isOtaUpgradeable": true,
    "isFlashable": false,
    "chipType": "cc2652r",
    "fileName": "es_ild_",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZDD01",
    "deviceCategory": "KZDD",
    "dmDeviceCategory": 5,
    "dmDeviceType": 1,
    "bleDeviceName": "KZED01",
    "categoryDisplayName": "Zigbee Drivers",
    "typeDisplayName": "E-Driver V2",
    "isOtaUpgradeable": true,
    "isFlashable": false,
    "chipType": "cc2652r",
    "fileName": "edriver_",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZRGBWWA01",
    "deviceCategory": "KZRGBWWA",
    "dmDeviceCategory": 8,
    "dmDeviceType": 1,
    "bleDeviceName": "KZCVS01",
    "categoryDisplayName": "CV Strip",
    "typeDisplayName": "RGBWWA V2",
    "isOtaUpgradeable": true,
    "isFlashable": false,
    "chipType": "cc2652r",
    "fileName": "cvstrip_cc",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "KEUSZIGBEE",
    "deviceType": "KZRFFAN01",
    "deviceCategory": "KZRFFAN",
    "dmDeviceCategory": 6,
    "dmDeviceType": 20,
    "bleDeviceName": "KZRFFANM1",
    "categoryDisplayName": "RF Fan controller",
    "typeDisplayName": "RF DC fan",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "fan_rf_",
    "KPN_Name": "RFFCDC01",
    "KPN_List": ""
  },
  {
    "protocol": "IP",
    "deviceType": "VDP01",
    "deviceCategory": "VDP",
    "dmDeviceCategory": 0,
    "dmDeviceType": 0,
    "bleDeviceName": "",
    "categoryDisplayName": "UNIFI VDP",
    "typeDisplayName": "UNIFI VDP",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "IP",
    "deviceType": "VDP02",
    "deviceCategory": "VDP",
    "dmDeviceCategory": 0,
    "dmDeviceType": 0,
    "bleDeviceName": "",
    "categoryDisplayName": "DAHUA VDP",
    "typeDisplayName": "DAHUA VDP",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "IP",
    "deviceType": "VDP03",
    "deviceCategory": "VDP",
    "dmDeviceCategory": 0,
    "dmDeviceType": 0,
    "bleDeviceName": "",
    "categoryDisplayName": "HIKVISION VDP",
    "typeDisplayName": "HIKVISION VDP",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "IP",
    "deviceType": "CCTV01",
    "deviceCategory": "CCTV",
    "dmDeviceCategory": 0,
    "dmDeviceType": 0,
    "bleDeviceName": "",
    "categoryDisplayName": "UNIFI CCTV",
    "typeDisplayName": "UNIFI CCTV",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "IP",
    "deviceType": "CCTV02",
    "deviceCategory": "CCTV",
    "dmDeviceCategory": 0,
    "dmDeviceType": 0,
    "bleDeviceName": "",
    "categoryDisplayName": "DAHUA CCTV",
    "typeDisplayName": "DAHUA CCTV",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "IP",
    "deviceType": "CCTV03",
    "deviceCategory": "CCTV",
    "dmDeviceCategory": 0,
    "dmDeviceType": 0,
    "bleDeviceName": "",
    "categoryDisplayName": "HIKVISION CCTV",
    "typeDisplayName": "HIKVISION CCTV",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "ZIGBEE3",
    "deviceType": "SZDL01",
    "deviceCategory": "SZDL",
    "dmDeviceCategory": 12,
    "dmDeviceType": 0,
    "bleDeviceName": "",
    "categoryDisplayName": "YALE LOCK",
    "typeDisplayName": "DOOR LOCK",
    "isOtaUpgradeable": false,
    "isFlashable": false,
    "chipType": "",
    "fileName": "",
    "KPN_Name": "",
    "KPN_List": ""
  },
  {
    "protocol": "ZIGBEE",
    "deviceType": "KZDMX",
    "deviceCategory": "KZCV6",
    "dmDeviceCategory": 8,
    "dmDeviceType": 24,
    "bleDeviceName": "KZDMX",
    "categoryDisplayName": "CV6",
    "typeDisplayName": "DMX",
    "isOtaUpgradeable": true,
    "isFlashable": true,
    "chipType": "cc2652p",
    "fileName": "dmx_",
    "KPN_Name": "",
    "KPN_List": ""
  }
]